import type { DailyVerse } from "./types";

/**
 * Daily encouragement verses. Text is the World English Bible (WEB), public domain.
 */
export const DAILY_VERSES: DailyVerse[] = [
  { ref: "Psalm 46:1", text: "God is our refuge and strength, a very present help in trouble.", translation: "WEB" },
  { ref: "Isaiah 41:10", text: "Don’t you be afraid, for I am with you. Don’t be dismayed, for I am your God. I will strengthen you. Yes, I will help you. Yes, I will uphold you with the right hand of my righteousness.", translation: "WEB" },
  { ref: "Philippians 4:6-7", text: "In nothing be anxious, but in everything, by prayer and petition with thanksgiving, let your requests be made known to God. And the peace of God, which surpasses all understanding, will guard your hearts and your thoughts in Christ Jesus.", translation: "WEB" },
  { ref: "Philippians 4:13", text: "I can do all things through Christ, who strengthens me.", translation: "WEB" },
  { ref: "Matthew 11:28", text: "Come to me, all you who labor and are heavily burdened, and I will give you rest.", translation: "WEB" },
  { ref: "Matthew 11:29", text: "Take my yoke upon you and learn from me, for I am gentle and humble in heart; and you will find rest for your souls.", translation: "WEB" },
  { ref: "John 14:27", text: "Peace I leave with you. My peace I give to you; not as the world gives, I give to you. Don’t let your heart be troubled, neither let it be fearful.", translation: "WEB" },
  { ref: "John 14:1", text: "Don’t let your heart be troubled. Believe in God. Believe also in me.", translation: "WEB" },
  { ref: "Romans 8:28", text: "We know that all things work together for good for those who love God, for those who are called according to his purpose.", translation: "WEB" },
  { ref: "Psalm 23:1", text: "A Psalm by David. The LORD is my shepherd; I shall lack nothing.", translation: "WEB" },
  { ref: "Psalm 23:4", text: "Even though I walk through the valley of the shadow of death, I will fear no evil, for you are with me. Your rod and your staff, they comfort me.", translation: "WEB" },
  { ref: "Proverbs 3:5-6", text: "Trust in the LORD with all your heart, and don’t lean on your own understanding. In all your ways acknowledge him, and he will make your paths straight.", translation: "WEB" },
  { ref: "Joshua 1:9", text: "Haven’t I commanded you? Be strong and courageous. Don’t be afraid. Don’t be dismayed, for the LORD your God is with you wherever you go.”", translation: "WEB" },
  { ref: "Isaiah 40:31", text: "But those who wait for the LORD will renew their strength. They will mount up with wings like eagles. They will run, and not be weary. They will walk, and not faint.", translation: "WEB" },
  { ref: "Isaiah 40:29", text: "He gives power to the weak. He increases the strength of him who has no might.", translation: "WEB" },
  { ref: "Psalm 34:18", text: "The LORD is near to those who have a broken heart, and saves those who have a crushed spirit.", translation: "WEB" },
  { ref: "Matthew 6:34", text: "Therefore don’t be anxious for tomorrow, for tomorrow will be anxious for itself. Each day’s own evil is sufficient.", translation: "WEB" },
  { ref: "Matthew 6:33", text: "But seek first God’s Kingdom and his righteousness; and all these things will be given to you as well.", translation: "WEB" },
  { ref: "Matthew 6:26", text: "See the birds of the sky, that they don’t sow, neither do they reap, nor gather into barns. Your heavenly Father feeds them. Aren’t you of much more value than they?", translation: "WEB" },
  { ref: "Lamentations 3:22-23", text: "It is because of the LORD’s loving kindnesses that we are not consumed, because his mercies don’t fail. They are new every morning. Great is your faithfulness.", translation: "WEB" },
  { ref: "Psalm 121:1-2", text: "I will lift up my eyes to the hills. Where does my help come from? My help comes from the LORD, who made heaven and earth.", translation: "WEB" },
  { ref: "Deuteronomy 31:6", text: "Be strong and courageous. Don’t be afraid or scared of them, for the LORD your God himself is who goes with you. He will not fail you nor forsake you.”", translation: "WEB" },
  { ref: "Isaiah 26:3", text: "You will keep whoever’s mind is steadfast in perfect peace, because he trusts in you.", translation: "WEB" },
  { ref: "John 16:33", text: "I have told you these things, that in me you may have peace. In the world you have trouble; but cheer up! I have overcome the world.", translation: "WEB" },
  { ref: "2 Corinthians 12:9", text: "He has said to me, “My grace is sufficient for you, for my power is made perfect in weakness.” Most gladly therefore I will rather glory in my weaknesses, that the power of Christ may rest on me.", translation: "WEB" },
  { ref: "Romans 15:13", text: "Now may the God of hope fill you with all joy and peace in believing, that you may abound in hope, in the power of the Holy Spirit.", translation: "WEB" },
  { ref: "Psalm 55:22", text: "Cast your burden on the LORD and he will sustain you. He will never allow the righteous to be moved.", translation: "WEB" },
  { ref: "Psalm 27:1", text: "By David. The LORD is my light and my salvation. Whom shall I fear? The LORD is the strength of my life. Of whom shall I be afraid?", translation: "WEB" },
  { ref: "Psalm 27:14", text: "Wait for the LORD. Be strong, and let your heart take courage. Yes, wait for the LORD.", translation: "WEB" },
  { ref: "Psalm 56:3", text: "When I am afraid, I will put my trust in you.", translation: "WEB" },
  { ref: "Nahum 1:7", text: "The LORD is good, a stronghold in the day of trouble; and he knows those who take refuge in him.", translation: "WEB" },
  { ref: "Psalm 91:1-2", text: "He who dwells in the secret place of the Most High will rest in the shadow of the Almighty. I will say of the LORD, “He is my refuge and my fortress; my God, in whom I trust.”", translation: "WEB" },
  { ref: "2 Timothy 1:7", text: "For God didn’t give us a spirit of fear, but of power, love, and self-control.", translation: "WEB" },
  { ref: "Romans 8:38-39", text: "For I am persuaded that neither death, nor life, nor angels, nor principalities, nor things present, nor things to come, nor powers, nor height, nor depth, nor any other created thing will be able to separate us from God’s love which is in Christ Jesus our Lord.", translation: "WEB" },
  { ref: "Isaiah 43:2", text: "When you pass through the waters, I will be with you, and through the rivers, they will not overflow you. When you walk through the fire, you will not be burned, and flame will not scorch you.", translation: "WEB" },
  { ref: "Isaiah 43:19", text: "Behold, I will do a new thing. It springs out now. Don’t you know it? I will even make a way in the wilderness, and rivers in the desert.", translation: "WEB" },
  { ref: "Psalm 30:5", text: "For his anger is but for a moment. His favor is for a lifetime. Weeping may stay for the night, but joy comes in the morning.", translation: "WEB" },
  { ref: "Psalm 118:24", text: "This is the day that the LORD has made. We will rejoice and be glad in it!", translation: "WEB" },
  { ref: "Psalm 16:8", text: "I have set the LORD always before me. Because he is at my right hand, I shall not be moved.", translation: "WEB" },
  { ref: "Philippians 4:19", text: "My God will supply every need of yours according to his riches in glory in Christ Jesus.", translation: "WEB" },
  { ref: "2 Corinthians 4:16", text: "Therefore we don’t faint, but though our outward person is decaying, yet our inward person is renewed day by day.", translation: "WEB" },
  { ref: "Galatians 6:9", text: "Let’s not be weary in doing good, for we will reap in due season if we don’t give up.", translation: "WEB" },
  { ref: "James 1:5", text: "But if any of you lacks wisdom, let him ask of God, who gives to all liberally and without reproach, and it will be given to him.", translation: "WEB" },
  { ref: "Psalm 32:8", text: "I will instruct you and teach you in the way which you shall go. I will counsel you with my eye on you.", translation: "WEB" },
  { ref: "Psalm 119:105", text: "Your word is a lamp to my feet, and a light for my path.", translation: "WEB" },
  { ref: "1 John 4:18", text: "There is no fear in love; but perfect love casts out fear, because fear has punishment. He who fears is not made perfect in love.", translation: "WEB" },
  { ref: "Psalm 139:9-10", text: "If I take the wings of the dawn, and settle in the uttermost parts of the sea, even there your hand will lead me, and your right hand will hold me.", translation: "WEB" },
  { ref: "Psalm 147:3", text: "He heals the broken in heart, and binds up their wounds.", translation: "WEB" },
  { ref: "Matthew 5:4", text: "Blessed are those who mourn, for they shall be comforted.", translation: "WEB" },
  { ref: "2 Corinthians 1:3-4", text: "Blessed be the God and Father of our Lord Jesus Christ, the Father of mercies and God of all comfort, who comforts us in all our affliction, that we may be able to comfort those who are in any affliction, through the comfort with which we ourselves are comforted by God.", translation: "WEB" },
  { ref: "Psalm 4:8", text: "In peace I will both lay myself down and sleep, for you alone, LORD, make me live in safety.", translation: "WEB" },
  { ref: "Colossians 3:15", text: "And let the peace of God rule in your hearts, to which also you were called in one body, and be thankful.", translation: "WEB" },
  { ref: "1 Thessalonians 5:16-18", text: "Always rejoice. Pray without ceasing. In everything give thanks, for this is the will of God in Christ Jesus toward you.", translation: "WEB" },
  { ref: "Psalm 107:1", text: "Give thanks to the LORD, for he is good, for his loving kindness endures forever.", translation: "WEB" },
  { ref: "Hebrews 11:1", text: "Now faith is assurance of things hoped for, proof of things not seen.", translation: "WEB" },
  { ref: "Psalm 46:10", text: "“Be still, and know that I am God. I will be exalted among the nations. I will be exalted on the earth.”", translation: "WEB" },
  { ref: "Psalm 73:26", text: "My flesh and my heart fails, but God is the strength of my heart and my portion forever.", translation: "WEB" },
  { ref: "Hebrews 4:16", text: "Let’s therefore draw near with boldness to the throne of grace, that we may receive mercy and may find grace for help in time of need.", translation: "WEB" },
  { ref: "Psalm 28:7", text: "The LORD is my strength and my shield. My heart has trusted in him, and I am helped. Therefore my heart greatly rejoices. With my song I will thank him.", translation: "WEB" },
  { ref: "James 1:17", text: "Every good gift and every perfect gift is from above, coming down from the Father of lights, with whom can be no variation, nor turning shadow.", translation: "WEB" },
  { ref: "Psalm 103:12", text: "As far as the east is from the west, so far has he removed our transgressions from us.", translation: "WEB" },
  { ref: "Psalm 145:18", text: "The LORD is near to all those who call on him, to all who call on him in truth.", translation: "WEB" },
];
